config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :products
  root 'products#index'

  resources :order_items, only: [:create, :destroy] do
    resources :addresses, except: [:index, :destroy]
  end

  resource :carts, only: [:show]

  resources :addresses, except: [:index, :destroy]

  get '/support', to: 'static_pages#support_page'
  resources :messages, only: [:create, :show]

end

app/models/address.rb
class Address < ApplicationRecord
  validates :first_name, :address, :last_name, :city, presence: true, length: { minimum: 2 }
  validates :options, length: { minimum: 2 }, allow_blank: true

  belongs_to :order
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/image.rb
class Image < ApplicationRecord
  validates :image, presence: true

  belongs_to :product

  mount_uploader :image, ImageUploader
end

app/models/message.rb
class Message < ApplicationRecord
  validates :name,      presence: true, length: { minimum: 1 }
  validates :last_name, presence: true, length: { minimum: 1 }
  validates :msg_body,  presence: true, length: { minimum: 1 }
  validates :email,     presence: true, length: { minimum: 1 }
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :order_items, validate: true
  has_many :products, through: :order_items
#  belongs_to :user

  has_one :address

  def add_product(product)
    current_order_items = order_items.find_by(product_id: product[:product_id])
     if current_order_items
       current_order_items.quantity += product[:quantity].to_i
       current_order_items.save
     else
       create_order_items = order_items.create(product_id: product[:product_id], quantity: product[:quantity],
                                               order_id: self.id)
     end
  end

  ##TODO minus_product_buy

end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :product, foreign_key: 'product_id'
  belongs_to :order,   foreign_key: 'order_id'

  validates :order_id,   presence: true
  validates :product_id, presence: true
  validates :quantity,   presence: true, numericality: { only_integer: true, greater_than: 0 }
  validates :unit_price, presence: true

  before_validation :copy_price

  validate :check_quantity_product

  def calculate_price
    self.unit_price * quantity
  end

  private

  def check_quantity_product
    errors.add(:product_quantity, "invalid product quantity") if self.product.quantity <= 0
  end

  def copy_price
    self.unit_price = self.product.price
  end
end

app/models/product.rb
class Product < ApplicationRecord
  validates :name,        presence: true, length: {minimum: 2}
  validates :description, presence: true, length: {minimum: 2}
  validates :price,       presence: true
  validates :category,    presence: true
  validates :quantity,    presence: true, numericality: { only_integer: true, greater_than: 0 }

  has_many :order_items
  has_many :orders, through: :order_items
  has_many :images, inverse_of: :product

  CategoryName = %w[Souvenirs Сups Caps Pendents]

  extend FriendlyId
  friendly_id :name

  accepts_nested_attributes_for :images, reject_if: :all_blank, allow_destroy: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  #has_many :orders
end

app/controllers/addresses_controller.rb
class AddressesController < ApplicationController
  before_action :find_address, only: [:show, :edit, :update]

  def new
    @address = Address.new
  end

  def create
    @order = current_order
    binding.pry
    @address = @order.build_address(addresses_params)
    if @address.save
      flash.now[:success] = 'Added your address'
      redirect_to @address
    else
      render :new
    end
  end

  def edit; end

  def update
    if @address.update_attributes(addresses_params)
      flash.now[:success] = 'Update information about your address'
      redirect_to @address
    else
      render :edit
    end
  end

  def show; end

  private

  def find_address
    @address = Address.find(params[:id])
  end

  def addresses_params
    params.require(:address).permit(:first_name, :last_name, :city, :address, :options)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_order
  add_flash_types :success, :info, :danger, :primary, :dark, :light

  private

  def current_order
    if session[:order_id]
      Order.find(session[:order_id])
    else
      Order.create
    end
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def show
    @cart = current_order
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

  def create
    @message = Message.new(messages_params)
    if @message.save
      redirect_to @message, success: 'Message is sended'
    else
      redirect_to @message, danger: 'Opps we have problems'
    end
  end

  def show
    @message = Message.find(params[:id])
  end

  private

  def messages_params
    params.require(:message).permit(:msg_body, :name, :last_name, :email)
  end
end

app/controllers/order_items_controller.rb
class OrderItemsController < ApplicationController

  def create
    @order = current_order
    @order.add_product(orders_items_params)
    session[:order_id] = @order.id
    find_product = Product.find(params[:order_item][:product_id])
    redirect_to product_path(find_product), success: "#{find_product.name} added to cart"
  end

  def destroy
    @order = current_order
    @item = @order.order_items.find(params[:id])
    @item.destroy
    redirect_to carts_path
  end

  private

  def orders_items_params
    params.require(:order_item).permit(:product_id, :quantity)
  end
end

app/controllers/products_controller.rb
  class ProductsController < ApplicationController
  before_action :find_product, only: [:edit, :update, :destroy, :show]

  def index
    @products ||= Product.order(:category)
    @cart = current_order.order_items
  end

  def new
    @product = Product.new
    @category = Product::CategoryName
  end

  def create
    @product = Product.new(products_params)
    if @product.save
      redirect_to @product, success: 'Create'
    else
      render :new
    end
  end

  def edit; end

  def update
    if @product.update_attributes(products_params)
      redirect_to  @product, success: "#{@product.name} is updated"
    else
      render :edit
    end
  end

  def show
    @order_items = current_order.order_items.new
  end

  def destroy
    if @pproduct.destroy
      redirect_to :index
    else
      redirect_to @product, danger: 'We are can not delete this product'
    end
  end

  private

  def find_product
    @product = Product.friendly.find(params[:id])
  end

  def products_params
    params.require(:product).permit(:name, :description, :price, :category, :quantity, images_attributes: [:id, :image, :_destroy] )
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def support_page
    @message = Message.new
  end
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
    return '' if resource.errors.empty?

    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    html = <<-HTML
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
      <button type="button" class="close" data-dismiss="alert">
        <span aria-hidden="true">&times;</span>
      </button>
      <strong>
       #{pluralize(resource.errors.count, "error")} must be fixed
      </strong>
      #{messages}
    </div>
    HTML

    html.html_safe
  end
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/addresses/_form.html.haml
=simple_form_for(@address) do |f|
  =f.input :first_name
  =f.input :last_name
  =f.input :city
  =f.input :address
  =f.input  :options
  =f.button :submit

app/views/addresses/edit.html.haml
=render('form')

app/views/addresses/new.html.haml
=render('form')

app/views/addresses/show.html.haml
address -show

app/views/carts/show.html.erb
<% if @cart.order_items.any? %>
  <table class="table">
    <thead>
    <tr>
      <th scope="col">Product</th>
      <th scope="col">Quanity</th>
      <th scope="col">Unit_price</th>
      <th scope="col">Price for the positions</th>
    </tr>
    </thead>
    <tbody>
    <% @cart.order_items.each do |cart| %>
    <tr>
      <th scope="row"><%= link_to cart.product.name, product_path(cart.product) %>
                      <%= link_to  order_item_path(cart), method: :delete, data: { confirm: 'Are your want delete product from cart' } do %>
                        <i class="fas fa-trash"></i><% end %>
      </th>
      <td><%= cart.quantity %></td>
      <td><%= cart.unit_price %></td>
      <td><%= cart.calculate_price %></td>
    </tr>
    <% end %>
    <tr>
      <th scope="row"> Total price:</th>
      <td></td>
      <td>Number_calculate_method</td>
    </tr>
    </tbody>
  </table>
  <%= link_to 'Add address', new_order_item_address_path(@cart) %>
<% else %>
  <h2>Your cart empty</h2>
  <%= link_to 'Go back', root_path %>
<% end %>

app/views/messages/show.html.haml
-provide(:title, "Message by #{@message.name}")
message-show page
=@message.name
=@message.last_name
=@message.email
=@message.msg_body

app/views/products/_form.html.haml
=simple_form_for(@product) do |f|
  =f.input :name,         placeholder: 'Write name product', label: false
  =f.input :description,  placeholder: 'Describe the product', label: false, as: :text
  =f.input :category,     collection: @category, prompt: 'Select category product', label: false
  =f.input :price
  =f.input :quantity
  =f.simple_fields_for :images do |image|
    =render 'image_fields', f: image
  .links
    =link_to_add_association 'Add Image', f, :images, class: 'btn btn-success'
  =f.button :submit

app/views/products/_image_fields.html.haml
.nested-fields
  =f.input :image, as: :file
  =link_to_remove_association "Delete Image", f

app/views/products/_product.html.haml
.col-4
  %h3=link_to "#{product.name}", product_path(product)
  =#link_to(image_tag(product.images.first.image.url(:thumb), class: 'rounded mx-auto d-block', alt: "#{product.name}" ), product_path(product)) if product.images.first.image?

app/views/products/edit.html.haml
edit
=render 'form'

app/views/products/index.html.haml
index
.row.justify-content-center
  =render @products

app/views/products/new.html.haml
new
=render 'form'

app/views/products/show.html.haml
show
.row.justify-content-md-center
  .col-10
    .row.product_show
      .image.pull-left#show_image
        =image_tag @product.images.first.image.url( :thumb ), class: 'img-thumbnail' if @product.images.any?
      .button_block.pull-rigth
        %p
          %h3=@product.description
        Price: #{@product.price}</br>
        In the presence: #{@product.quantity}
        =simple_form_for( @order_items, url: order_items_path ) do |f|
          =f.input_field :product_id, as: :hidden, value: @product.id
          =f.input :quantity, min: 1
          =f.button :submit, 'To Cart'

app/views/static_pages/support_page.html.haml
=simple_form_for(@message, url:  messages_path) do |f|
  =f.input :name, label: 'Your name'
  =f.input :last_name, label: 'Your surname'
  =f.input :email, as: :email
  =f.input :msg_body,  label: 'Body message', as: :text
  =f.button :submit